CREATE TABLE IF NOT EXISTS persons(
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(128) NOT NULL,
    Surname VARCHAR(128) NOT NULL,
    Patronymic VARCHAR(128),
    Age INTEGER  NOT NULL,
    Gender VARCHAR(8) NOT NULL,
    Nationality VARCHAR(128) NOT NULL
);
