CREATE TABLE IF NOT EXISTS persons(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(128) NOT NULL,
    Surname VARCHAR(128) NOT NULL,
    Patronymic VARCHAR(128),
    Age INTEGER  NOT NULL,
    Gender VARCHAR(8) NOT NULL,
    Nationality VARCHAR(128) NOT NULL,
    Created_at TIMESTAMP NOT NULL DEFAULT_NOW(),
    Updated_at TIMESTAMP NOT NULL DEFAULT_NOW(),
);
